dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=binance setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: jQO9sXbeRRW1IM8kxfu4wp+AY4wz36A0eTiUjqxXgDsUqgV3biSvCD1Fj89Oaq39ydrzFik520iP5jDkr9iik8+8GKEqWAmf0DcAlwi0sYFuKX/BNbLESjhn2x5ty09De33zEN18h+uWUWISwSY7X5/bpo5/X0scZm6vX6PkEAdIZ1oCSbqWG4QtbVDjb93/jIk1r4PBgYXCOsAYNPccYZ1kan4Xo9hG4RQBO/tCFtoicdfvI7SMlxzTt9lmmuwHnNIF0TOuZVA2H8H9Bh5v7+6vO/EfidMMs7n9r9scD8xquTBiOVkhWsg936BQqFCCI04Y73OyKG5+BKPjACMNb7PZa/eq2QCUoCtBOVi+qK2cPrPW7lDhh5snPiJjV4bwS74M1mTwW5tpmjPhQ9a9QyJv87XjtQJvq8UL1la9nrNxYvlzQz/yaxu49CnPzbykjzH4xbEOU9tFOanwQNcU8/bHIYp0g6kB+KmU+vS68Yp3ypy2aoG2c4uDOj3xEngSzedtHC+v4QyyYNIMp+1fDUC61FJGeh6GG539OPCUJO9hz2IT3zB8lZlawfp7OaNk9DYUjfiJrQuB6mjSN0Cbk48vkBrAPIVOpagDh7+Wc9JmrziPymPWuIfNAPkZepU4wVOQLcQ8UHHDXZq9wzIthUPGY4Hh/81SLEKOKdJZtXk=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
